# Generated by Django 5.0 on 2025-01-18 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField()),
                ('passport_number', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('nic', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='nic number not valid', regex='^(([5,6,7,8,9]{1})([0-9]{1})([0,1,2,3,5,6,7,8]{1})([0-9]{6})([v|V|x|X]))|(([1,2]{1})([0,9]{1})([0-9]{2})([0,1,2,3,5,6,7,8]{1})([0-9]{7}))')])),
                ('mobile', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lankan phone number.', regex='^(?:7|0|(?:\\+94))[0-9]{9,10}$')])),
                ('telephone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lankan telephone number.', regex='0((11)|(2(1|[3-7]))|(3[1-8])|(4(1|5|7))|(5(1|2|4|5|7))|(6(3|[5-7]))|([8-9]1))[0-9]{7}')])),
                ('email', models.TextField(validators=[django.core.validators.RegexValidator(message='Email not valid', regex='^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$')])),
                ('address', models.TextField()),
            ],
        ),
    ]
