# Generated by Django 5.0 on 2025-01-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
