# Generated by Django 5.0 on 2025-01-19 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapp', '0002_rename_firstname_passenger_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.TextField(unique=True, validators=[django.core.validators.RegexValidator(message='Email not valid', regex='^[\\w.\\-]+@[\\w.\\-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='mobile',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Sri Lankan phone number.', regex='^(?:7|0|(?:\\+94))[0-9]{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nic',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='nic number not valid', regex='^(([5,6,7,8,9]{1})([0-9]{1})([0,1,2,3,5,6,7,8]{1})([0-9]{6})([v|V|x|X]))|(([1,2]{1})([0,9]{1})([0-9]{2})([0,1,2,3,5,6,7,8]{1})([0-9]{7}))')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='registration_number',
            field=models.IntegerField(unique=True),
        ),
    ]
